import { MoodCapsule } from '../types/mood';

export const MOOD_CAPSULES: MoodCapsule[] = [
  {
    id: 'latenight',
    label: 'Late Night',
    emoji: '🌙',
    tagline: 'Deep bass & midnight introspections',
    dominantColor: '#4F46E5',
    secondaryColor: '#818CF8',
    energyRange: [0.2, 0.6],
    preferredGenres: ['R&B', 'Synthwave', 'Midnight Pop', 'Lo-Fi', 'Electronic'],
  },
  {
    id: 'focus',
    label: 'Focus',
    emoji: '☀️',
    tagline: 'Deep flow & steady concentration',
    dominantColor: '#0EA5E9',
    secondaryColor: '#38BDF8',
    energyRange: [0.3, 0.55],
    preferredGenres: ['Ambient', 'Lo-Fi', 'Instrumental', 'Classical', 'Chillhop'],
  },
  {
    id: 'energy',
    label: 'Energy',
    emoji: '⚡',
    tagline: 'High tempo, workout & adrenaline',
    dominantColor: '#EF4444',
    secondaryColor: '#F97316',
    energyRange: [0.7, 1.0],
    preferredGenres: ['Dance', 'Electronic', 'Hip-Hop', 'Rock', 'Drum & Bass'],
  },
  {
    id: 'feels',
    label: 'Feels',
    emoji: '🫶',
    tagline: 'Soulful melodies & emotive resonance',
    dominantColor: '#EC4899',
    secondaryColor: '#F472B6',
    energyRange: [0.3, 0.65],
    preferredGenres: ['Indie', 'Acoustic', 'Soul', 'Bedroom Pop', 'Ballad'],
  },
  {
    id: 'drive',
    label: 'Drive',
    emoji: '🚗',
    tagline: 'Night highways & rhythmic cruising',
    dominantColor: '#8B5CF6',
    secondaryColor: '#A78BFA',
    energyRange: [0.55, 0.85],
    preferredGenres: ['Synthwave', 'Alternative', 'Indie Rock', 'Electro Pop'],
  },
  {
    id: 'chill',
    label: 'Chill',
    emoji: '☁️',
    tagline: 'Unwind, relax & drift away',
    dominantColor: '#10B981',
    secondaryColor: '#34D399',
    energyRange: [0.15, 0.45],
    preferredGenres: ['Downtempo', 'Jazz', 'Chillhop', 'Acoustic', 'Neo-Soul'],
  },
  {
    id: 'discover',
    label: 'Discover',
    emoji: '✦',
    tagline: 'Hidden gems from your personal archive',
    dominantColor: '#F59E0B',
    secondaryColor: '#FBBF24',
    energyRange: [0.2, 0.9],
    preferredGenres: ['All'],
  },
];
